service: story
frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-2
  profile: macbook
  stage: ${opt:stage, 'dev'}

custom:
  storyGeneratorArn: arn:aws:lambda:ap-southeast-2:${account.id}:function:story-generator
  imageGeneratorArn: arn:aws:lambda:ap-southeast-2:${account.id}:function:image-generator
  voiceCreatorArn: arn:aws:lambda:ap-southeast-2:${account.id}:function:voice-creato
  

resources:
  Resources:
    NameTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
        BillingMode: PAY_PER_REQUEST
        TableName: 'names'

    ScenesTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
        BillingMode: PAY_PER_REQUEST
        TableName: 'scenes'

    StoryTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: 'NEW_IMAGE'
        TableName: 'stories'
    
    StoryBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: 'story-bucket93790wef9'

    DynamoDBStreamEventSourceMapping:
      Type: 'AWS::Lambda::EventSourceMapping'
      Properties:
        BatchSize: 100
        Enabled: true
        EventSourceArn: !GetAtt StoryTable.StreamArn
        FunctionName: "image-generator"
        StartingPosition: LATEST
        MaximumRetryAttempts: 1


    ImageLambdaInvokePermission: #permission to invoke image generator func when a story is entered in Dynamodb
      Type: "AWS::Lambda::Permission"
      Properties:
        Action: "lambda:InvokeFunction"
        FunctionName: !Ref imageGeneratorArn
        Principal: "dynamodb.amazonaws.com"
        SourceArn: !GetAtt StoryTable.StreamArn

    VoiceLambdaInvokePermission: #permission to invoke Voice creator func when a story is entered in Dynamodb
      Type: "AWS::Lambda::Permission"
      Properties:
        Action: "lambda:InvokeFunction"
        FunctionName: !Ref voiceCreatorArn
        Principal: "dynamodb.amazonaws.com"
        SourceArn: !GetAtt StoryTable.StreamArn

    ImageDynamoDBStreamEventSourceMapping:
      Type: 'AWS::Lambda::EventSourceMapping'
      Properties:
        BatchSize: 100
        Enabled: true
        EventSourceArn: !GetAtt StoryTable.StreamArn
        FunctionName: !Ref imageGeneratorArn
        StartingPosition: LATEST
        MaximumRetryAttempts: 1

    VoiceDynamoDBStreamEventSourceMapping:
      Type: 'AWS::Lambda::EventSourceMapping'
      Properties:
        BatchSize: 100
        Enabled: true
        EventSourceArn: !GetAtt StoryTable.StreamArn
        FunctionName: !Ref voiceCreatorArn
        StartingPosition: LATEST
        MaximumRetryAttempts: 1

  Outputs:
    NameTableArn:
      Value: !GetAtt NameTable.Arn
      Export:
        Name: NameTableArn
    ScenesTableArn:
      Value: !GetAtt ScenesTable.Arn
      Export:
        Name: ScenesTableArn
    StoryTableArn:
      Value: !GetAtt StoryTable.Arn
      Export:
        Name: StoryTableArn


